version: '2'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: voter-cache
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - /data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend
    
  voter-api:
    image: voter-api:latest
    container_name: voter
    restart: always
    ports:
      - '2080:2080'
    depends_on:
      cache:
        condition: service_started
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend

  poll-api:
    image: poll-api:latest
    container_name: poll
    restart: always
    ports:
      - '3080:3080'
    depends_on:
      cache:
        condition: service_started
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend

  votes-api:
    image: votes-api:latest
    container_name: votes
    restart: always
    ports:
      - '1080:1080'
    depends_on:
      cache:
        condition: service_started
    environment:
      - REDIS_URL=cache:6379
      - VOTER_URL=voter-api:2080
      - POLL_URL=poll-api:3080
    networks:
      - frontend
      - backend


networks:
  frontend:
    internal: false
  backend:
    internal: true