version: '2'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: voter-cache
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - /data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend
    
  votes-api:
    image: votes:v1
    container_name: votes
    restart: always
    ports:
      - '1080:1080'
    depends_on:
      cache:
        condition: service_completed_successfully
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend
networks:
  frontend:
    internal: false
  backend:
    internal: true