version: '2'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: voter-cache
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - /data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend
    
  votes-api:
    image: voter-api:latest
    container_name: voter
    restart: always
    ports:
      - '2080:2080'
    depends_on:
      cache:
        condition: service_started
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend
networks:
  frontend:
    internal: false
  backend:
    internal: true